on:
  push:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile client.py
    - run: pyinstaller --onefile gui.py
    - run: pyinstaller --onefile server.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
