on:
  push:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile -i iconclient.ico client.py
    - run: pyinstaller --onefile -i iconclient.ico gui.py
    - run: pyinstaller --onefile -i iconserver.ico server.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
